version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/MoneyTransfer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Qriv7ye2_me92
    depends_on:
      db:
        condition: service_healthy


  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: MoneyTransfer
      MYSQL_ROOT_PASSWORD: Qriv7ye2_me92
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s


volumes:
  db_data: